# TYPE  DATABASE        USER            ADDRESS                 METHOD

# 本地
local   all             all                                     trust

# 容器内
host    all             all             127.0.0.1/32            trust

# 内网（Docker网络）
host    all             all             172.22.0.0/16           md5

# 允许所有外部（测试环境用，生产不要这么开）
host    all             all             0.0.0.0/0               md5

# IPv6
host    all             all             ::/0                    scram-sha-256